
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed May 29 12:32:43 CST 2024
//----------------------------------------------------

package Dev;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Procedure = 10;
  public static final int Parentesis_c = 4;
  public static final int Cadena = 8;
  public static final int End = 6;
  public static final int Parentesis_a = 3;
  public static final int EOF = 0;
  public static final int Identificador = 2;
  public static final int PuntoComa = 7;
  public static final int error = 1;
  public static final int Signos = 9;
  public static final int Begin = 5;
}

